server:
  port: 8080
spring:
  application:
    name: "TwitterKafkaProducer"
apis:
  twitter:
    credentials:
      consumerKey: ''
      consumerSecret: ''
      token: ''
      secret: ''
  weather:
    url: 'https://weatherapi-com.p.rapidapi.com'
    headers:
      rapidapi-host: 'weatherapi-com.p.rapidapi.com'
      credentials:
        rapidapi-key: ''
